// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt6Qg82bWYzUU8d3lQIPOuRNQIWGNUL6g',
    appId: '1:151590535937:web:f12a555b64d415a1f55100',
    messagingSenderId: '151590535937',
    projectId: 'handicap-tracker-1d0ec',
    authDomain: 'handicap-tracker-1d0ec.firebaseapp.com',
    storageBucket: 'handicap-tracker-1d0ec.firebasestorage.app',
    measurementId: 'G-RZRXXT8TXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2_yI-n0k8_hKqalywEJO01T4ZpVkrjIE',
    appId: '1:151590535937:android:20432151ca0a6879f55100',
    messagingSenderId: '151590535937',
    projectId: 'handicap-tracker-1d0ec',
    storageBucket: 'handicap-tracker-1d0ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5i_5gNDUnThqXNP-t4DmAJ7GIbqq_JE8',
    appId: '1:151590535937:ios:6a1d70c65bdc321cf55100',
    messagingSenderId: '151590535937',
    projectId: 'handicap-tracker-1d0ec',
    storageBucket: 'handicap-tracker-1d0ec.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5i_5gNDUnThqXNP-t4DmAJ7GIbqq_JE8',
    appId: '1:151590535937:ios:6a1d70c65bdc321cf55100',
    messagingSenderId: '151590535937',
    projectId: 'handicap-tracker-1d0ec',
    storageBucket: 'handicap-tracker-1d0ec.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt6Qg82bWYzUU8d3lQIPOuRNQIWGNUL6g',
    appId: '1:151590535937:web:1bb73c7c196fd96bf55100',
    messagingSenderId: '151590535937',
    projectId: 'handicap-tracker-1d0ec',
    authDomain: 'handicap-tracker-1d0ec.firebaseapp.com',
    storageBucket: 'handicap-tracker-1d0ec.firebasestorage.app',
    measurementId: 'G-S0T71QZZW7',
  );
}
